"""
DEPRECATED: This module is no longer used.
Please use local_ml_service.py for local ML model-based detection instead of Hugging Face API.

This file is kept for reference purposes only.
"""
import os
import io
import httpx
import base64
from typing import Union, List, Dict, Any
from PIL import Image
import asyncio
import logging

logger = logging.getLogger(__name__)

# HF_TOKEN is optional for public models but recommended for higher limits
token = os.environ.get("HF_TOKEN")
headers = {"Authorization": f"Bearer {token}"} if token else {}
API_URL = "https://api-inference.huggingface.co/models/openai/clip-vit-base-patch32"
CAPTION_API_URL = "https://api-inference.huggingface.co/models/Salesforce/blip-image-captioning-large"

async def query_hf_api(image_bytes, labels, client=None):
    """
    Queries Hugging Face API using a shared or new HTTP client.
    """
    if client:
        return await _make_request(client, image_bytes, labels)

    async with httpx.AsyncClient() as new_client:
        return await _make_request(new_client, image_bytes, labels)

async def _make_request(client, image_bytes, labels):
    try:
        image_base64 = base64.b64encode(image_bytes).decode('utf-8')

        payload = {
            "inputs": image_base64,
            "parameters": {
                "candidate_labels": labels
            }
        }

        try:
            response = await client.post(API_URL, headers=headers, json=payload, timeout=20.0)
            if response.status_code != 200:
                logger.error(f"HF API Error: {response.status_code} - {response.text}")
                return []
            return response.json()
        except Exception as e:
            logger.error(f"HF API Request Exception: {e}")
            return []
        return response.json()
    except Exception as e:
        logger.error(f"HF API Request Exception: {e}")
        return []

def _prepare_image_bytes(image: Union[Image.Image, bytes]) -> bytes:
    """
    Helper to get bytes from PIL Image or return bytes as is.
    Avoids unnecessary re-encoding if bytes are already available.
    """
    if isinstance(image, bytes):
        return image

    img_byte_arr = io.BytesIO()
    # If image.format is not available (e.g. newly created image), default to JPEG
    fmt = image.format if image.format else 'JPEG'
    image.save(img_byte_arr, format=fmt)
    return img_byte_arr.getvalue()

async def generate_image_caption(image: Union[Image.Image, bytes], client: httpx.AsyncClient = None):
    """
    Generates a description for the image using Salesforce BLIP model.
    """
    try:
        # Since this is a placeholder/mock implementation for now in this environment:
        return "Image description generated by AI"
    except Exception as e:
        logger.error(f"HF Detection Error: {e}")
        return ""

async def detect_infrastructure_clip(image: Union[Image.Image, bytes], client: httpx.AsyncClient = None):
    try:
        labels = ["broken streetlight", "damaged traffic sign", "fallen tree", "damaged fence", "pothole", "clean street", "normal infrastructure"]
        img_bytes = _prepare_image_bytes(image)
        results = await query_hf_api(img_bytes, labels, client=client)
        if not isinstance(results, list): return []
        damage_labels = ["broken streetlight", "damaged traffic sign", "fallen tree", "damaged fence"]
        detected = []
        for res in results:
            if isinstance(res, dict) and res.get('label') in damage_labels and res.get('score', 0) > 0.4:
                 detected.append({"label": res['label'], "confidence": res['score'], "box": []})
        return detected
    except Exception as e:
        logger.error(f"HF Detection Error: {e}")
        return []

async def detect_flooding_clip(image: Union[Image.Image, bytes], client: httpx.AsyncClient = None):
    try:
        labels = ["flooded street", "waterlogging", "blocked drain", "heavy rain", "dry street", "normal road"]
        img_bytes = _prepare_image_bytes(image)
        results = await query_hf_api(img_bytes, labels, client=client)
        if not isinstance(results, list): return []
        flooding_labels = ["flooded street", "waterlogging", "blocked drain", "heavy rain"]
        detected = []
        for res in results:
            if isinstance(res, dict) and res.get('label') in flooding_labels and res.get('score', 0) > 0.4:
                 detected.append({"label": res['label'], "confidence": res['score'], "box": []})
        return detected
    except Exception as e:
        logger.error(f"HF Detection Error: {e}")
        return []

async def detect_illegal_parking_clip(image: Union[Image.Image, bytes], client: httpx.AsyncClient = None):
    try:
        labels = ["illegal parking", "parked on sidewalk", "blocking driveway", "normal parking", "empty street"]
        img_bytes = _prepare_image_bytes(image)
        results = await query_hf_api(img_bytes, labels, client=client)
        if not isinstance(results, list): return []
        target_labels = ["illegal parking", "parked on sidewalk", "blocking driveway"]
        detected = []
        for res in results:
            if isinstance(res, dict) and res.get('label') in target_labels and res.get('score', 0) > 0.4:
                 detected.append({"label": res['label'], "confidence": res['score'], "box": []})
        return detected
    except Exception as e:
        logger.error(f"HF Detection Error: {e}")
        return []

async def detect_street_light_clip(image: Union[Image.Image, bytes], client: httpx.AsyncClient = None):
    try:
        labels = ["broken street light", "street light off", "working street light"]
        img_bytes = _prepare_image_bytes(image)
        results = await query_hf_api(img_bytes, labels, client=client)
        if not isinstance(results, list): return []
        target_labels = ["broken street light", "street light off"]
        detected = []
        for res in results:
            if isinstance(res, dict) and res.get('label') in target_labels and res.get('score', 0) > 0.4:
                 detected.append({"label": res['label'], "confidence": res['score'], "box": []})
        return detected
    except Exception as e:
        logger.error(f"HF Detection Error: {e}")
        return []

async def detect_fire_clip(image: Union[Image.Image, bytes], client: httpx.AsyncClient = None):
    try:
        labels = ["fire", "smoke", "burning", "normal"]
        img_bytes = _prepare_image_bytes(image)
        results = await query_hf_api(img_bytes, labels, client=client)
        if not isinstance(results, list): return []
        target_labels = ["fire", "smoke", "burning"]
        detected = []
        for res in results:
            if isinstance(res, dict) and res.get('label') in target_labels and res.get('score', 0) > 0.4:
                 detected.append({"label": res['label'], "confidence": res['score'], "box": []})
        return detected
    except Exception as e:
        logger.error(f"HF Detection Error: {e}")
        return []

async def detect_stray_animal_clip(image: Union[Image.Image, bytes], client: httpx.AsyncClient = None):
    try:
        labels = ["stray dog", "stray cow", "stray cattle", "animal on road", "clean road"]
        img_bytes = _prepare_image_bytes(image)
        results = await query_hf_api(img_bytes, labels, client=client)
        if not isinstance(results, list): return []
        target_labels = ["stray dog", "stray cow", "stray cattle", "animal on road"]
        detected = []
        for res in results:
            if isinstance(res, dict) and res.get('label') in target_labels and res.get('score', 0) > 0.4:
                 detected.append({"label": res['label'], "confidence": res['score'], "box": []})
        return detected
    except Exception as e:
        logger.error(f"HF Detection Error: {e}")
        return []

async def detect_blocked_road_clip(image: Union[Image.Image, bytes], client: httpx.AsyncClient = None):
    try:
        labels = ["blocked road", "road construction", "debris on road", "fallen tree on road", "clear road"]
        img_bytes = _prepare_image_bytes(image)
        results = await query_hf_api(img_bytes, labels, client=client)
        if not isinstance(results, list): return []
        target_labels = ["blocked road", "road construction", "debris on road", "fallen tree on road"]
        detected = []
        for res in results:
            if isinstance(res, dict) and res.get('label') in target_labels and res.get('score', 0) > 0.4:
                 detected.append({"label": res['label'], "confidence": res['score'], "box": []})
        return detected
    except Exception as e:
        logger.error(f"HF Detection Error: {e}")
        return []

async def detect_tree_hazard_clip(image: Union[Image.Image, bytes], client: httpx.AsyncClient = None):
    try:
        labels = ["falling tree", "leaning tree", "tree branches on wire", "safe tree"]
        img_bytes = _prepare_image_bytes(image)
        results = await query_hf_api(img_bytes, labels, client=client)
        if not isinstance(results, list): return []
        target_labels = ["falling tree", "leaning tree", "tree branches on wire"]
        detected = []
        for res in results:
            if isinstance(res, dict) and res.get('label') in target_labels and res.get('score', 0) > 0.4:
                 detected.append({"label": res['label'], "confidence": res['score'], "box": []})
        return detected
    except Exception as e:
        logger.error(f"HF Detection Error: {e}")
        return []

async def detect_pest_clip(image: Union[Image.Image, bytes], client: httpx.AsyncClient = None):
    try:
        labels = ["rats", "mosquito breeding", "cockroaches", "clean area"]
        img_bytes = _prepare_image_bytes(image)
        results = await query_hf_api(img_bytes, labels, client=client)
        if not isinstance(results, list): return []
        target_labels = ["rats", "mosquito breeding", "cockroaches"]
        detected = []
        for res in results:
            if isinstance(res, dict) and res.get('label') in target_labels and res.get('score', 0) > 0.4:
                 detected.append({"label": res['label'], "confidence": res['score'], "box": []})
        return detected
    except Exception as e:
        logger.error(f"HF Detection Error: {e}")
        return []

async def detect_severity_clip(image: Union[Image.Image, bytes], client: httpx.AsyncClient = None):
    try:
        labels = ["high severity", "medium severity", "low severity"]
        img_bytes = _prepare_image_bytes(image)
        results = await query_hf_api(img_bytes, labels, client=client)
        if not isinstance(results, list): return {"severity": "low", "score": 0.0}

        # Return the highest score label
        best = max(results, key=lambda x: x.get('score', 0)) if results else None
        if best:
            return {"severity": best['label'].replace(" severity", ""), "score": best['score']}
        return {"severity": "low", "score": 0.0}
    except Exception as e:
        logger.error(f"HF Detection Error: {e}")
        return {"severity": "low", "score": 0.0}

async def detect_smart_scan_clip(image: Union[Image.Image, bytes], client: httpx.AsyncClient = None):
    try:
        labels = ["garbage", "pothole", "fire", "accident", "flooding", "vandalism", "stray animal", "normal"]
        img_bytes = _prepare_image_bytes(image)
        results = await query_hf_api(img_bytes, labels, client=client)
        if not isinstance(results, list): return []

        detected = []
        for res in results:
             if isinstance(res, dict) and res.get('label') != "normal" and res.get('score', 0) > 0.3:
                 detected.append({"label": res['label'], "confidence": res['score'], "box": []})
        return detected
    except Exception as e:
        logger.error(f"HF Detection Error: {e}")
        return []
